Adds circle.yml file for continuous integration
lvarayut/relay-fullstack pull request #71
Opened 2017-02-17 19:40 UTC by ncrmro

2017-02-17 21:39 UTC, Neitsch requested changes

2017-02-17 21:39 UTC, Neitsch commented on circle.yml
> +      - npm run build-server
Either choose yarn or npm.

2017-02-17 21:49 UTC, ncrmro commented on circle.yml
> +      - npm run build-server
Yarn is used to install dependencies and npm is just piggybacking on package.json commands.

Yarn is much faster to install dependencies, wouldn't you agree?

2017-02-17 21:57 UTC, Neitsch commented on circle.yml
> +      - npm run build-server
Yes, absolutely, but why use npm at all? Just use yarn run

2017-02-17 22:10 UTC, Neitsch approved these changes

2017-02-17 22:11 UTC, ncrmro commented on circle.yml
> +      - npm run build-server
Still not sure of everything yarn can do, switched commands 👍

2017-02-20 03:02 UTC, Neitsch commented
@lvarayut will you enable CI?

2017-02-20 04:21 UTC, lvarayut commented
Yes, I will enable it very soon.

2017-02-20 15:18 UTC, lvarayut commented
@ncrmro, @Neitsch, I normally use Travis as my CI, which seems to be very fast and easy to use. Just wanted to know your preference before merging this PR. What do you prefer between Travis or you still want to go with CircleCI?

2017-02-20 15:31 UTC, Neitsch commented
I'm also a Travis guy, but why not try Circle CI out? ;)

2017-02-20 17:27 UTC, ncrmro commented
@lvarayut  @Neitsch circle ci is is also quite fast they have 4gb ram builds. I've used them pretty extensively. Not much experience with Travis myself

2017-02-21 14:07 UTC, lvarayut commented
Alright. Let's try that out 👍

2017-02-21 14:07 UTC, merged

2017-02-21 19:52 UTC, ncrmro commented
@lvarayut @Neitsch Whooo!